export const LOGIN = 'LOGIN';

export const ADD_USER = 'ADD_USER'


export const PACKAGE = 'PACKAGE'
export const FETCH_PACKAGES_REQUEST= 'FETCH_PACKAGES_REQUEST'
export const FETCH_PACKAGES_SUCCESS = 'FETCH_PACKAGES_SUCCESS'
export const FETCH_PACKAGES_FAILURE = 'FETCH_PACKAGES_FAILURE'
export const  DELETE_TOUR_PACKAGE_REQUEST = 'DELETE_TOUR_PACKAGE_REQUEST'
export const DELETE_TOUR_PACKAGE_SUCCESS = 'DELETE_TOUR_PACKAGE_SUCCESS'
export const DELETE_TOUR_PACKAGE_FAILURE = 'DELETE_TOUR_PACKAGE_FAILURE'
export const UPDATE_TOUR_PACKAGE_REQUEST = 'UPDATE_TOUR_PACKAGE_REQUEST'
export const UPDATE_TOUR_PACKAGE_SUCCESS = 'UPDATE_TOUR_PACKAGE_SUCCESS'
export const UPDATE_TOUR_PACKAGE_FAILURE = 'UPDATE_TOUR_PACKAGE_FAILURE'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS= "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

export const BOOK_TOUR_REQUEST = 'BOOK_TOUR_REQUEST'
export const BOOK_TOUR_SUCCESS = 'BOOK_TOUR_SUCCESS'
export const BOOK_TOUR_FAILURE = 'BOOK_TOUR_FAILURE'
export const FETCH_BOOKINGS_REQUEST = 'FETCH_BOOKINGS_REQUEST';
export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS';
export const FETCH_BOOKINGS_FAILURE = 'FETCH_BOOKINGS_FAILURE';
export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE';
export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAILURE = 'ADD_CONTACT_FAILURE';
